title:               Lagrange
tagline:             a minimalist Jekyll theme
email:               your-email@domain.com
description:         
baseurl:             "" # the subpath of your site, e.g. /blog
url:                 "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:    jekyllrb
github_username:     jekyll

# Build settings
markdown:            kramdown
